# Generated by Django 3.1.5 on 2021-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number_phone',
            field=models.IntegerField(default=1, max_length=17),
            preserve_default=False,
        ),
    ]
